Change FBC logic to not call IIB only when ocp_version >=4.13
release-engineering/pubtools-quay pull request #158
Opened 2023-02-13 17:50 UTC by yashvardhannanavati

Stonesoup intends to start supporting indexes only from OCP v4.13

2023-02-14 02:31 UTC, emilyzheng commented on pubtools/_quay/operator_pusher.py
> +                    "as it supports both <= 4.13 and >= 4.12 and is opted in FBC: {item}".format(
Should be '<=4.12 and >=4.13' or '<4.13 and > 4.12'?

2023-02-14 03:20 UTC, chandwanitulsi reviewed
minor change, other than that looks good

2023-02-14 07:08 UTC, querti requested changes

2023-02-14 07:08 UTC, querti commented on pubtools/_quay/operator_pusher.py
>                          + "from iib build as it's opted in for FBC and targeting OCP version >4.10"
This is incorrect, right?

2023-02-14 13:52 UTC, midnightercz reviewed
The Change looks good, but you need to fix log messages

2023-02-14 14:41 UTC, yashvardhannanavati commented on pubtools/_quay/operator_pusher.py
>                          + "from iib build as it's opted in for FBC and targeting OCP version >4.10"
Nice catch! Changing it.

2023-02-14 15:02 UTC, yashvardhannanavati commented on pubtools/_quay/operator_pusher.py
>                          + "from iib build as it's opted in for FBC and targeting OCP version >4.10"
Done

2023-02-14 21:31 UTC, chandwanitulsi approved these changes

2023-02-15 01:49 UTC, emilyzheng approved these changes

2023-02-15 07:06 UTC, querti approved these changes

2023-02-15 07:34 UTC, lipoja approved these changes

2023-02-20 17:15 UTC, merged