Allow radas messaging address to be formatable
release-engineering/pubtools-quay pull request #185
Opened 2023-09-04 08:03 UTC by midnightercz

2023-09-04 10:02 UTC, querti approved these changes

2023-09-04 10:36 UTC, zxiong approved these changes

2023-09-05 02:41 UTC, emilyzheng requested changes

2023-09-05 02:41 UTC, emilyzheng commented on pubtools/_quay/signature_handler.py
> +        radas_address.format(task_id=self.task_id)
This doesn't change string radas_address.

2023-09-05 02:41 UTC, emilyzheng commented on pubtools/_quay/signature_handler.py
> +            radas_address=docker_settings.get("umb_radas_address", radas_address),
Getting address from settings again? And not formatting with task_id?

2023-09-06 01:23 UTC, emilyzheng approved these changes

2023-09-06 06:19 UTC, merged