Unique task-id tags when pushing prerelease content
release-engineering/pubtools-quay pull request #187
Opened 2023-09-07 17:11 UTC by midnightercz

Pubtools-quay call IIB to build index images with version + task-id to ensure there's preserved history of all builds requested by pub in IIB. For prerelease operators, as there's one build per operator, in the case of more operators it means same version + task-id tag is used for all of them.
That's why in the case of prerelease operators, also transformed advisory id is used

2023-09-08 09:00 UTC, emilyzheng requested changes

2023-09-08 09:00 UTC, emilyzheng commented on pubtools/_quay/operator_pusher.py
> +                        "{0}-{1}-{2}".format(index_image.split(":")[1], self.task_id, group)
group includes ":" which shouldn't be in an image tag.

2023-09-11 12:24 UTC, querti reviewed
It's hard to review this without proper context. Could you explain in the commit message what this change accomplishes and why it is necessary?

2023-09-11 12:46 UTC, midnightercz commented
> It's hard to review this without proper context. Could you explain in the commit message what this change accomplishes and why it is necessary?

I just added a description

2023-09-11 12:50 UTC, querti approved these changes

2023-09-12 05:04 UTC, emilyzheng approved these changes

2023-09-12 06:16 UTC, merged