Fixes from testing
release-engineering/pubtools-quay pull request #199
Opened 2023-11-16 11:55 UTC by midnightercz

- Set src quay client instead of dest client for generate_to_sign
- Fixed wrong docs for remove_repo, clear_repo

2023-11-17 09:32 UTC, zxiong commented
@midnightercz, can you add signing to pub task jsonl log?

2023-11-20 09:16 UTC, querti requested changes

2023-11-20 09:16 UTC, querti commented on pubtools/_quay/clear_repo.py
> +    # print(existing_manifests)
print

2023-11-20 09:16 UTC, querti commented on pubtools/_quay/clear_repo.py
> +    print("OUTDATED MANIFESTS", outdated_manifests)
print

2023-11-22 02:37 UTC, emilyzheng approved these changes

2023-11-22 07:37 UTC, querti approved these changes

2023-11-23 06:56 UTC, merged